### ISSUE TITLE
Alteryx v10??

### ISSUE THREAD

**Issue by JochemZ** [tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries#1]
I copied the dll's but there are no tools in my GUI after starting the client?
Any idea??

**Comment by tobiasmh** [comment]
A new build is available here that is compatible with Alteryx V10. (They will be in the Laboratory section)
https://github.com/tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries/tree/master/Release/0.1/AlteryxV10_Compatible

**Comment by JochemZ** [comment]
Hi Tobias,

Thnx for your effort, but for me this is still not working.
I don’t see the ldap tools in the laboratory section.

I copied the new dll’s to the bin/plugin folder.

Jochem


Van: Tobias Montagna-Hay [mailto:notifications@github.com]
Verzonden: maandag 23 november 2015 3:09
Aan: tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries <Alteryx-Ldap-Input-Plugin-Binaries@noreply.github.com>
CC: Jochem Zwienenberg | Victa <jz@victa.nl>
Onderwerp: Re: [Alteryx-Ldap-Input-Plugin-Binaries] Alteryx v10?? (#1)


A new build is available here that is compatible with Alteryx V10. (They will be in the Laboratory section)
https://github.com/tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries/tree/master/Release/0.1/AlteryxV10_Compatible

**Comment by tobiasmh** [comment]
To confirm you are using the 64bit of Alteryx GUI Designer?

**Comment by JochemZ** [comment]
Yes

Verstuurd vanaf mijn iPhone

Op 23 nov. 2015 om 09:45 heeft Tobias Montagna-Hay <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


To confirm you are using the 64bit of Alteryx GUI Designer?

-

**Comment by tobiasmh** [comment]
Can you check that Windows is not blocking the DLL?

https://github.com/tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries/blob/master/Documentation/Screenshots/UnblockDLL.png

**Comment by JochemZ** [comment]
Yes it was blocking the file!
But after unblocking the file, it is still not in my Laboratory tools, did a restart of Alteryx.

Met vriendelijke groet,
Jochem Zwienenberg

Senior Business Consultant / Product Manager


[Victa Qlik Solutions]<https://www.victa.nl/>


t:

+31(0)74-2915208

m:

+31(0)6-14305579

e:

jz@victa.nl<mailto:jz@victa.nl>

w:

www.victa.nl


Deze email is uitsluitend bestemd voor geadresseerde(n). Indien deze e-mail niet voor u is bestemd,
verzoeken wij u om contact op te nemen met de afzender en daarna het bericht te vernietigen.

Victa B.V. is bij de Kamer van Koophandel geregistreerd onder nummer 08225460.
Van: Tobias Montagna-Hay [mailto:notifications@github.com]
Verzonden: maandag 23 november 2015 10:03
Aan: tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries <Alteryx-Ldap-Input-Plugin-Binaries@noreply.github.com>
CC: Jochem Zwienenberg | Victa <jz@victa.nl>
Onderwerp: Re: [Alteryx-Ldap-Input-Plugin-Binaries] Alteryx v10?? (#1)


Can you check that Windows is not blocking the DLL?

https://github.com/tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries/blob/master/Documentation/Screenshots/UnblockDLL.png

**Comment by tobiasmh** [comment]
Sorry to just double check, you have unblocked both DLL files? Especially the LdapInputGui.dll file?

**Comment by JochemZ** [comment]
Yes i did

Van: Tobias Montagna-Hay [mailto:notifications@github.com]
Verzonden: maandag 23 november 2015 10:16
Aan: tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries <Alteryx-Ldap-Input-Plugin-Binaries@noreply.github.com>
CC: Jochem Zwienenberg | Victa <jz@victa.nl>
Onderwerp: Re: [Alteryx-Ldap-Input-Plugin-Binaries] Alteryx v10?? (#1)


Sorry to just double check, you have unblocked both DLL files? Especially the LdapInputGui.dll file?

**Comment by tobiasmh** [comment]
Did you manage to resolve this?

This issue may have some helpful tips: https://github.com/tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries/releases/tag/0.2

**Comment by JochemZ** [comment]
No we did it by SQL and a Linked server

Verstuurd vanaf mijn iPhone

Op 26 mrt. 2016 om 05:43 heeft Tobias Montagna-Hay <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Did you manage to resolve this?

This issue may have some helpful tips: https://github.com/tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries/releases/tag/0.2

-
