### ISSUE TITLE
LDAP Format other than Microsoft OS

### ISSUE THREAD

**Issue by fkhan4** [tobiasmh/Alteryx-Ldap-Input-Plugin-Binaries#5]
Hi @tobiasmh ,

Does this module work on LDAP formats other than the standard microsoft OS?
I was trying with the following format, but it throws on an error:

Username: cn=ldsuser,o=admin

**Comment by tobiasmh** [comment]
What error does it give you?

**Comment by fkhan4** [comment]
Hi,

Thanks for getting back to me . 
The error is as follow:
"ParseError: Invalid character reference at line 1 and column 1522 while processing "AlteryxModule"

I suspect it is on the validation check for username. 

Regards,
Farhana Khan

**Comment by tobiasmh** [comment]
I have not tried it with a non Active Directory server. Are you using OpenLDAP?

Internally the DLL references Winldap.h which uses the Microsoft implementation of the LDAP API. That said I can't see anything that stands out to me as not being compatible with the OpenLDAP implementation.

If you don't supply a username do you get a different error?

**Comment by fkhan4** [comment]
Hi,

I never thought to try that, I just did and it worked! Thanks so much!!

Regards,
FK

**Comment by tobiasmh** [comment]
Nice!

**Comment by fkhan4** [comment]
Hi,

Thanks for getting back to me .
The error is as follow:
"ParseError: Invalid character reference at line 1 and column 1522 while
processing "AlteryxModule"

I suspect it is on the validation check for username.



Regards,
Farhana Khan
